version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.prod
    container_name: api
    ports:
      - "3003:3003"
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DATABASE}
      DRAGONFLY_HOST: redis  
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
      GOOGLE_REDIRECT_URI: ${GOOGLE_REDIRECT_URI}
      OPENAI_API_KEY: ${OPENAI_API_KEY}

    networks:
      - postgres-network 
      - mynetwork

  postgres:
    image: postgres:latest
    container_name: postgres_container
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DATABASE}
    networks:
      - postgres-network  

  redis:  
    image: redis:latest
    container_name: redis_container
    networks:
      - mynetwork

networks:
  postgres-network:
    driver: bridge
  mynetwork:
    driver: bridge
