name: Deploy to Google Cloud Run

on:
  push:
    branches:
      - prod 

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v0
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v0
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_CREDENTIALS }}

      - name: Build Docker image
        run: docker build -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/your-docker-image:latest -f Dockerfile.prod .

      - name: Push Docker image
        run: docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/your-docker-image:latest

      - name: Deploy to Google Cloud Run
        run: |
          gcloud run deploy your-cloud-run-service \
            --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/your-docker-image:latest \
            --region us-central1 \
            --platform managed \
            --allow-unauthenticated
